import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import { Eyebrow, FinalCTA, PageHero, Reveal, imagery } from "@/components/nivaa";

export const Route=createFileRoute("/portfolio")({head:()=>({meta:[{title:"Interior Design Portfolio — NIVAA"},{name:"description",content:"Explore NIVAA's residential, commercial, hospitality and retail interior design portfolio."},{property:"og:title",content:"Spaces with Stories — NIVAA Portfolio"},{property:"og:description",content:"A collection of thoughtful interiors made to be lived in."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:PortfolioPage});
const projects=[
 {name:"Serene Villa",place:"Jamnagar",cat:"Residential",img:imagery.living,tall:true},
 {name:"Urban Haven",place:"Mumbai",cat:"Residential",img:imagery.dining,tall:true},
 {name:"The Calm Home",place:"Rajkot",cat:"Residential",img:imagery.living,tall:true},
 {name:"Modern Retreat",place:"Ahmedabad",cat:"Hospitality",img:imagery.dining},
 {name:"Brew & Beyond",place:"Café Interior",cat:"Hospitality",img:imagery.dining},
 {name:"Workspace Reimagined",place:"Bengaluru",cat:"Office",img:imagery.retail},
 {name:"The Label House",place:"Retail Store",cat:"Retail",img:imagery.retail},
 {name:"Skyline Escapes",place:"Penthouse",cat:"Commercial",img:imagery.living},
];
const filters=["All","Residential","Commercial","Hospitality","Office","Retail"];
function PortfolioPage(){const [filter,setFilter]=useState("All");const visible=projects.filter(p=>filter==="All"||p.cat===filter);return <main><PageHero eyebrow="Our Portfolio" title={<>Spaces<br/>with Stories</>} copy="Every space we design is a reflection of a unique journey. Explore our work and see how ideas turn into beautiful, livable spaces." cta="Start Your Project" image={imagery.dining}/>
<section className="py-20"><div className="shell"><div className="mb-10 flex flex-wrap gap-2" role="group" aria-label="Filter projects">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-full px-5 py-2 text-xs transition-colors ${filter===f?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground hover:text-foreground"}`}>{f}</button>)}</div><motion.div layout className="grid auto-rows-[12rem] grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><AnimatePresence mode="popLayout">{visible.map((p,i)=><motion.article layout initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.97}} transition={{duration:.35}} key={p.name} className={`group relative overflow-hidden ${p.tall?"row-span-2":"row-span-1"} ${i===0?"sm:col-span-2 lg:col-span-1":""} ${i%3===0?"blob-a":"rounded-[2.5rem]"}`}><img src={p.img} alt={`${p.name}, ${p.place}`} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-foreground/65 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-5 text-primary-foreground"><div><h2 className="font-display text-2xl">{p.name}</h2><p className="text-[.58rem] uppercase tracking-[.12em]">{p.place}</p></div><span className="grid size-9 place-items-center rounded-full bg-background text-foreground"><ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></div></motion.article>)}</AnimatePresence><Reveal className="row-span-2 grid place-items-center rounded-[45%_15%_42%_12%] bg-muted p-9"><blockquote className="font-display text-3xl leading-tight">“<br/>Beautiful spaces happen when design meets purpose.</blockquote></Reveal></motion.div></div></section>
<section className="wave-top bg-sage py-20"><div className="shell grid gap-10 md:grid-cols-[1fr_3fr]"><h2 className="font-display text-4xl">Projects<br/>That Inspire</h2><div className="grid grid-cols-2 gap-8 md:grid-cols-4">{[["150+","Projects Completed"],["100+","Happy Clients"],["8+","Years of Experience"],["4","Cities"]].map(([n,t])=><div key={t} className="md:border-l md:border-foreground/15 md:pl-8"><strong className="font-display text-5xl font-normal">{n}</strong><p className="mt-2 text-xs text-muted-foreground">{t}</p></div>)}</div></div></section><FinalCTA conversation/></main>}