import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Building2, Home, Lamp, Leaf, Lightbulb, Palette, Pencil, Settings, Sparkles } from "lucide-react";
import { ArrowButton, Eyebrow, FinalCTA, PageHero, Reveal, imagery } from "@/components/nivaa";

export const Route=createFileRoute("/services")({head:()=>({meta:[{title:"Interior Design Services — NIVAA"},{name:"description",content:"Residential, commercial, styling and turnkey interior design services by NIVAA."},{property:"og:title",content:"Thoughtful Design for Every Space — NIVAA"},{property:"og:description",content:"End-to-end interior design, crafted around your life."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ServicesPage});
const services=[
 {n:"01",title:"Residential Interiors",copy:"Personalised homes that reflect your lifestyle and aspirations.",icon:Home,img:imagery.living},
 {n:"02",title:"Commercial Spaces",copy:"Workspaces that inspire productivity and growth.",icon:Building2,img:imagery.dining},
 {n:"03",title:"Furniture & Styling",copy:"Curated furniture, décor and styling to complete your space.",icon:Lamp,img:imagery.materials},
 {n:"04",title:"Turnkey Solutions",copy:"Hassle-free design and execution, from concept to handover.",icon:Settings,img:imagery.retail},
 {n:"05",title:"Space Refresh",copy:"Transform existing spaces with fresh ideas and simple changes.",icon:Leaf,img:imagery.dining},
];
const steps=[{n:"01",t:"Discover",c:"We understand your needs and vision.",i:Sparkles},{n:"02",t:"Plan",c:"We create a tailored design strategy.",i:Palette},{n:"03",t:"Design",c:"We bring ideas to life with detailed plans.",i:Pencil},{n:"04",t:"Execute",c:"We manage every detail with precision.",i:Settings},{n:"05",t:"Deliver",c:"You step into a space you'll love.",i:Home}];
function ServicesPage(){return <main><PageHero eyebrow="Our Services" title={<>Thoughtful<br/>Design for<br/>Every <em>Space</em></>} copy="From concept to completion, we design spaces that are functional, beautiful and deeply personal." cta="Book a Consultation"/>
<section className="py-24"><div className="shell"><div className="grid gap-8 md:grid-cols-2"><Reveal><Eyebrow>What We Offer</Eyebrow><h2 className="display-md">Our Services</h2></Reveal><p className="self-end text-sm leading-7 text-muted-foreground">Every space has a story. We offer end-to-end interior design services crafted to bring your vision to life—with elegance, intention and ease.</p></div><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-5">{services.map((s,i)=><Reveal key={s.title}><article className="group"><div className={`relative h-64 overflow-hidden ${i%2?"blob-b":"blob-a"}`}><img src={s.img} alt={s.title} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><span className="absolute bottom-0 left-0 grid size-14 place-items-center rounded-full bg-background"><s.icon className="size-6" strokeWidth={1.2}/></span></div><span className="mt-5 block text-[.6rem] text-muted-foreground">{s.n}</span><h3 className="mt-1 font-display text-2xl">{s.title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{s.copy}</p><span className="mt-4 inline-flex items-center gap-2 border-b border-foreground pb-1 text-xs">Explore <ArrowRight className="size-3"/></span></article></Reveal>)}</div></div></section>
<section className="wave-top bg-sage py-24"><div className="shell"><div className="grid gap-6 md:grid-cols-2"><Reveal><Eyebrow>Our Process</Eyebrow><h2 className="display-md">From Vision<br/>to Reality</h2></Reveal><p className="max-w-md self-end text-sm text-muted-foreground">A seamless journey, designed around you. Simple, collaborative and transparent.</p></div><div className="relative mt-16 grid gap-10 md:grid-cols-5 md:gap-5"><div className="absolute left-6 top-6 hidden h-px w-[calc(100%-3rem)] bg-foreground/20 md:block"/>{steps.map(s=><Reveal key={s.n}><div className="relative flex gap-5 md:block"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-background"><s.i className="size-5" strokeWidth={1.2}/></span><div><span className="mt-5 block font-display text-xl">{s.n}</span><h3 className="text-xs font-semibold uppercase">{s.t}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{s.c}</p></div></div></Reveal>)}</div></div></section>
<section className="py-24"><div className="shell grid items-center gap-14 md:grid-cols-2"><img src={imagery.materials} alt="Stone, wood and textile samples" width={1536} height={1024} loading="lazy" className="blob-a h-[30rem] w-full object-cover"/><Reveal><Eyebrow>Bespoke Solutions</Eyebrow><h2 className="display-md">Tailored to<br/><em>Your Lifestyle</em></h2><p className="mt-6 max-w-lg text-sm leading-7 text-muted-foreground">No two spaces are the same, and neither are our solutions. We design with your lifestyle, taste and budget in mind, creating spaces that feel uniquely yours.</p><div className="mt-7"><ArrowButton>Let&apos;s Discuss Your Project</ArrowButton></div></Reveal></div></section>
<section className="bg-muted/55 py-20"><div className="shell grid gap-12 md:grid-cols-[.7fr_1.3fr]"><Reveal><Eyebrow>Additional Services</Eyebrow><h2 className="display-md">Complete<br/>Your Space</h2></Reveal><div className="grid grid-cols-2 gap-8 md:grid-cols-4">{[[Lightbulb,"Lighting Design"],[Leaf,"Material Selection"],[Palette,"Art & Décor Curation"],[Sparkles,"Green & Sustainable Design"]].map(([Icon,title])=><div key={String(title)}><span className="grid size-16 place-items-center blob-a bg-background"><Icon className="size-6" strokeWidth={1.2}/></span><h3 className="mt-4 font-display text-lg">{String(title)}</h3></div>)}</div></div></section><FinalCTA/></main>}